services:
  web:
    container_name: "esprzedaz"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    working_dir: /var/www
    networks:
        - app-network

  php:
    container_name: "esprzedaz-backend"
    build:
      context: .
      dockerfile: Dockerfile
    image: "esprzedaz/php"
    ports:
      - "6001:6001"
    expose:
      - "9000"
    volumes:
      - ../../:/var/www
    working_dir: /var/www
    networks:
        - app-network

networks:
    app-network:
        driver: bridge
